### ISSUE TITLE
Feature: 将默认模板做成选项

### ISSUE THREAD

**Issue by KKKKilru** [WhiteMatrixTech/micro-service-gen-tool#3]
### Description
目前工具的模板是用户手动输入，可以将常用模板，例如grpc template做成默认选项

### Proposed solution
目前工具的模板是用户手动输入，可以将常用模板，例如grpc template做成默认选项
用户可以选择：
 1. grpc
 2. xxx
 3. xxx
 4. others
选完others用户自己输入url

**Comment by lwnmengjing** [comment]
完成
